### ISSUE TITLE
not working with ghcr.io

### ISSUE THREAD

**Issue by PH1P5** [SmartsquareGmbH/delete-old-packages#13]
Hi there,

it seams that when using this with **github container registry** the action does not work. We used it with the keep x images and sadly it does nothing.

As mentioned here, ghcr API should be able to handle query and delete requests:
https://github.community/t/you-can-now-delete-and-restore-any-package-type-within-github-packages/162393

Is it maybe caused by an outdated octokit version this action is in use of?

Thanks in advance for taking care of this
(would really like to use this action further)

**Comment by rubengees** [comment]
Hello!

This is because ghcr.io is not supported yet via the GraphQL API which this action uses. While it seems possible with the REST API I would rather wait for GraphQL support so this integrates better with the other package types.

Also, see: https://github.com/SmartsquareGmbH/delete-old-packages/issues/5

**Comment by PH1P5** [comment]
Ok i see. I will close this one in favor of #5 

Anyways, thank you for your efforts.
