### ISSUE TITLE
Packages published since August no longer deleted

### ISSUE THREAD

**Issue by Niek** [SmartsquareGmbH/delete-old-packages#25]
See: https://github.com/actions/delete-package-versions/issues/74#issuecomment-1301635935

This means that any new packages are no longer deleted.

**Comment by rubengees** [comment]
Thanks for the heads up. I hope that's not something they are planning for every package type since the GraphQL API is superior in what you can do with it.

Since this action already works with the ghcr.io containers, npm.pkg.github.com should also be possible to support. I'll see if I can get it to work.

**Comment by rubengees** [comment]
This now works in [v0.6.0](https://github.com/SmartsquareGmbH/delete-old-packages/releases/tag/v0.6.0) using the same mechanism we use for ghcr.io container packages.
