### ISSUE TITLE
When I specify a static version I get no matches

### ISSUE THREAD

**Issue by chrisjohnson00** [SmartsquareGmbH/delete-old-packages#3]
I have a process where I tag containers with the branch name.  I'd like to setup a workflow to delete the tag after the branch is deleted.  For some reason this doesn't work (this is a test, the real flow sets version pattern dynamically)

```
      - uses: smartsquaregmbh/delete-old-packages@v0.1.1
        with:
          version-pattern: "mytag"
```

Is there something special I need to add to the value to make it work like a regex?

**Comment by KCErb** [comment]
This looks a lot like the issue I was having. Turns out in the end that since this action grabs 20 versions and then does the regex filter, my version was not in the first 20.

That being said, if you're on version 0.1.1 it should be pulling 100 versions. Do you have 100 older versions than "mytag"?

In either case, I'm working on a PR right now to sidestep this problem by deleting the named version.

**Comment by chrisjohnson00** [comment]
Would that still affect the package if there is only a single version of it? I've only pushed a single tag thus far and can't get it to match and delete it.

**Comment by KCErb** [comment]
That's odd. I recommend that you try using the github graphql API explorer and seeing what comes up there when you use the query here.

https://developer.github.com/v4/explorer/

Oh! Hang on you just have one tag. And it defaults to keep = 2. So I'm guessing it won't delete it.

The PR I just opened addresses that as well, forcing 'keep' to 0 when you give a version number.

**Comment by chrisjohnson00** [comment]
Haha man I feel dumb. I will add keep 0 and close this if that resolves it

**Comment by KCErb** [comment]
Nah, I did that exact thing! So at least if you're dumb you've got company.

**Comment by chrisjohnson00** [comment]
adding `keep: 0` solved it... thanks!
